### PR TITLE
add German language

### PR DESCRIPTION
**Pull request by PiterGTX**
add German language

### CODE REVIEW

**Comment by PiterGTX** [comment]
actually it's a problem for me create my own npm package, because i'm new in js at all,  if it possible may you apply these changes?

**Comment by TerryZ** [comment]
Upgrade v-page version to `2.0.9` and you also can globally config plugin language like below

```js
import Vue from 'vue'
import Page from 'v-page'

Vue.use(Page, {
  language: 'de'
})
```

**Comment by PiterGTX** [comment]
thanks for language !

**Comment by PiterGTX** [comment]
i used it locally, but now it stop working, even doesn't exist like a component

import { vPage } from 'v-page'
export default {
  components: {
    'v-page': vPage
  }

and on a template

<v-page :total-row="100" align="left" :page-size-menu="false" :info="false"></v-page>

and it even don't plug in, now i have to plug in only globally ?

**Comment by TerryZ** [comment]
Try this

```js
import { Page } from 'v-page'

export default {
  components: {
    'v-page': Page
  }
}
```

**Comment by PiterGTX** [comment]
Super, it works :)) Tanks again!

**Pull request merged**
